### ISSUE TITLE
tranning?

### ISSUE THREAD

**Issue by Lakung** [upul/Behavioral-Cloning#1]
i'm very interested in this project, could you offer some more information in readme file for how to train the car?

**Comment by upul** [comment]
Appreciate I you could tell me, what kind of info are you looking for? Are you looking for 
1. Training, validation, testing and hyper-parameter selection process?
2. The hardware which I used to train the network?
3.  How to address overfitting and improve generalization and etc. 

Thanks,
Upul

**Comment by upul** [comment]
Answered hence, closing this issue
